export const CANDIDATES_SELECTED = 'CANDIDATES_SELECTED';
export const PROJECT_SELECTED = 'PROJECT_SELECTED';


// steps
export const steps = {
  SELECT: 'SELECT',
  ATTACH_PROJECT: 'ATTACH_PROJECT',
  MESSAGE: 'MESSAGE',
  CONFIRM: 'CONFIRM'
};
