export const CANDIDATE_ADD = 'CANDIDATE_ADD';
export const CANDIDATE_REMOVED = 'CANDIDATE_REMOVE';
export const CANDIDATES_SELECTED = 'CANDIDATES_SELECTED';
export const PROJECT_SELECTED = 'PROJECT_SELECTED';
export const MESSAGE_WRITTEN = 'MESSAGE_WRITTEN';
export const PREV_STEP = 'PREV_STEP';


// steps
export const steps = {
  SELECT: 'SELECT',
  ATTACH_PROJECT: 'ATTACH_PROJECT',
  MESSAGE: 'MESSAGE',
  CONFIRM: 'CONFIRM'
};
